### ISSUE TITLE
Flickering in link partial (need help)

### ISSUE THREAD

**Issue by nvh95** [nvh95/cv#4]
## Describe the bug

The link partial gets flickering when visiting https://cv.hung.dev

Reason:
- `nuxt`/ `vue-notion` need to recompute inline CSS to layout link partial. So, when JS is loaded, the UI will look as expected

## Screenshots
![Oct-27-2022 11-27-36](https://user-images.githubusercontent.com/8603085/198191527-2e917aca-efe9-457b-809a-47b21fe61e1f.gif)

## Reproduce

Just visit https://cv.hung.dev

## Expected behavior

UI should remain the same with or without Javascript

## Additional context

We might need to update the notion content, which is at https://hung.dev/cv (I am not sure how). But I prefer if we can resolve it by code itself

**Comment by huyng12** [comment]
Take a look at to the implementation of Column block [here](https://github.com/janniks/vue-notion/blob/6ae91c3c2a9e4175c64ddc8626b3dcbcd69b0ae7/src/blocks/column.vue#L2-L7).

You can see that the it is wrapped by `Fragment` component from [vue-fragment](https://github.com/Thunberg087/vue-fragment) which is not support SSR because of its idea. TLDR; It will render a div to wrap elements, then remove them on loaded. So that, DOM structure would be wrong in the first load (aka SSR).

I have an idea to work around that is override their styles to make its visual before/after loaded stay the same.

Check out my PR's changes for the implementation.
